### PR TITLE
title change

### PR DESCRIPTION
**Pull request by bduggan**
Just a small title change.  Also a question: where should the actual article go?

### CODE REVIEW

**Comment by zoffixznet** [comment]
> Also a question: where should the actual article go?

In your article :) The title-like stuff on this schedule is largely for other contributors to know roughly what you're writing about, so two authors don't accidentally end up writing about exactly the same thing.

**Comment by moritz** [comment]
@bduggan please tell me your email address or wordpress.com account, then I can send you and invitation. Then you can add the actual article at https://perl6advent.wordpress.com/wp-admin/

**Comment by bduggan** [comment]
Got it, thanks, @zoffixznet.

@moritz -- my wordpress account name is bdmatatu.  Thank you!

**Comment by moritz** [comment]
@bduggan I've sent a wordpress.com invitation your way. If you don't receive one in the next few minutes or hours, please speak up again.

**Comment by bduggan** [comment]
Got it, thanks!

**Pull request merged**
