### PR TITLE
Update schedule: "Language Independent Validation Rules (LIVR) for Perl6"

### PR DESCRIPTION
**Pull request by koorchik**

### CODE REVIEW

**Comment by AlexDaniel** [comment]
Thanks!

**Comment by AlexDaniel** [comment]
Ah. Do you already have an account on https://perl6advent.wordpress.com/ to create posts? If not, let @zoffixznet  know your email address and he'll send you a wordpress invite.

**Comment by moritz** [comment]
... or if you already have a wordpress.com account, the username is sufficient too, @koorchik

**Comment by koorchik** [comment]
Thanks. I've just contacted my @zoffixznet at twitter. Yes, I have an account, the username is koorchik

**Comment by moritz** [comment]
Invitation sent. CC @zoffixznet.

**Comment by moritz** [comment]
@koorchik how is your post coming along? Please contact me if you need any assistance, or have trouble making it on time.

**Comment by koorchik** [comment]
Hi @moritz, it is almost ready. Just want to add several more validation examples and upload it to WordPress.

**Comment by koorchik** [comment]
Hello guys, sorry for the delay. I use Rakudo on Windows and I was struggling with some issues. The post is ready and available here https://github.com/koorchik/perl6-livr-advent-calendar-post . Now I am trying to install Acme::Advent::Highlighter to upload the post to WordPress. I hope to finish within one hour

**Comment by zoffixznet** [comment]
FWIW, I ran the highlighter on your article right now and I think it's choking on the fact that you've used GitHub flavoured markdown for codeblocks instead of regular or Multi markdown. It sees a single codeblock only.

You may wish to just take HTML from [GitHub's render](https://github.com/koorchik/perl6-livr-advent-calendar-post/blob/master/README.md) and use that for the article, without syntax highlighting for Perl 6 (it's not mandatory).

**Comment by koorchik** [comment]
@zoffixznet thank you, fixed it (and tons of other issues too). I've saved the post as a draft at wordpress. What should I do next? Do you have access to it?

**Comment by zoffixznet** [comment]
With my articles, I just went to https://perl6advent.wordpress.com/wp-admin/edit.php then clicked "Edit" on my posts and on the right panel scheduled it for midnight for the day I was meant to post it on.

**Comment by koorchik** [comment]
@zoffixznet Thank you! Done. It says that it will be posted in 7 hours. As I see, it is in my timezone (Kyiv/Ukraine). I am not sure if is it an issue.

**Comment by zoffixznet** [comment]
We usually do UTC midnight, but since Ukraine is just +2 it's not really an issue, so if you rather not adjust it, then don't :)

**Comment by moritz** [comment]
I've changed the publication date/time to UTC midnight, just to be consistent with the other posts. Thanks @koorchik for the post!

**Comment by koorchik** [comment]
Hello guys,
Just want to ask if is it ok to repost the article at my company blog?

**Comment by AlexDaniel** [comment]
Sure, you have all the rights.

**Pull request merged**
